### ISSUE TITLE
Can't seem to get it to work.

### ISSUE THREAD

**Issue by moneydance** [sunshinekitty/vaultingkube#2]
Hi, I love the idea of this an I am trying it out in minikube. I can't seem to get it to work though. Vaultingkube seems to start up fine, but all I get is the message

'Started with sync period every 30 seconds message.'

When I edit a secret on my path it doesn't update.

My mount path is 

    secret/kubernetes

and I am trying to read

    secret/kubernetes/default/secrets/webtokens

Here are my environment variables.

        - name: VAULT_ADDR
          value: 'http://secrets-vault:8200'
        - name: VAULT_TOKEN
          value: abdefghijklmnopqrstuvwxyz
        - name: VK_DELETE_OLD
          value: 'true'
        - name: VK_SYNC_PERIOD
          value: '30'
        - name: VK_VAULT_ROOT_MOUNT_PATH
          value: secret/kubernetes

Maybe the ability to specify a more verbose debug would be helpful. Like every sync iteration listing the paths being read. I'm assuming I'd be getting an error message if I couldn't successfully connect to my vault instance so I don't think that's the issue.

**Comment by sfrique** [comment]
Did you figure it out?
