### ISSUE TITLE
Error if vault is using SSL

### ISSUE THREAD

**Issue by sfrique** [sunshinekitty/vaultingkube#3]
I get this error when using https for vault.

```
time="2018-04-25T20:17:30Z" level=fatal msg="Get https://vault.domain.com/v1/sys/mounts: x509: failed to load system roots and no roots provided" 
```

If i use internal vault (which also has ssl) I get wrong certificated as i should, but there is no option to skip it.

I've also built it, it didn't complain about ssh as i had the ca-certificates on pod, but i got and endless loop. 

I will debug more and open a new issue if i figure out the problem, but it's most likely related to the mount paths.

**Comment by ethan1341** [comment]
Also struggling with this some documentation would be nice.

**Comment by sfrique** [comment]
@ethan1341 I did my own build and some debug and got it working. I still need to actually build an image and etc... but i got the code to work on a alpine and building it manually.

What I failed to understand is that you have to create a mount on your vault with this path:

`[VK_VAULT_ROOT_MOUNT_PATH]/[NAMESPACE]/[SECRET_TYPE]/`

It doesn't work only create a secret on vault at corresponding path, you need to create the mount.

The documentation isn't clear about it as well, or I still didn't understand what happened, or docs are not clear, either way, at least i got it working for now.

I managed to understand that after looking this code:
https://github.com/sunshinekitty/vaultingkube/blob/d4c2c1df066ce10d7df3630db2b14dd99dd96379/comms/vault.go#L58

And this:
https://github.com/sunshinekitty/vaultingkube/blob/d4c2c1df066ce10d7df3630db2b14dd99dd96379/comms/vault.go#L64-L77

Hope that helps
