### ISSUE TITLE
Necessary Vault Policies

### ISSUE THREAD

**Issue by sfrique** [sunshinekitty/vaultingkube#6]
It would be nice to have documented the vault permissions needed for vaultingkube to work.

From my tests, it needs read to mounts and read and lists for the secrets, follows the rules:

```
{
  "path": {
      "sys/mounts": {
          "capabilities": [
            "read"
          ]
        }
    }
 }
```
```
{
  "path": {
      "${VK_VAULT_ROOT_MOUNT_PATH}/*": {
          "capabilities": [
            "read",
            "list"
          ]
        }
    }
}
```
OBS: Check the var!

Can't do the PR right now. At least there is some info here!

**Comment by sunshinekitty** [comment]
You're right, it should just be read and list.  I can eventually document this in the readme

https://github.com/sunshinekitty/vaultingkube/blob/master/comms/vault.go#L58
https://github.com/sunshinekitty/vaultingkube/blob/master/comms/vault.go#L95
https://github.com/sunshinekitty/vaultingkube/blob/master/comms/vault.go#L104

vaultingkube doesn't update/create anything on the Vault side, so nothing else [here](https://www.vaultproject.io/docs/concepts/policies.html#capabilities) should be needed

**Comment by sfrique** [comment]
Thanks!
