### ISSUE TITLE
How to use with a Vault server behind a self-signed certificate?

### ISSUE THREAD

**Issue by plombardi89** [sunshinekitty/vaultingkube#7]
I have a vault server I setup following the [Kelsey Hightower Vault on GKE guide](https://github.com/kelseyhightower/vault-on-google-kubernetes-engine) which has the user create a self-signed TLS certificate for communication with the vault server. There is no option to configure this in Vaultingkube and I would love some guidance.

```text
time="2018-07-30T04:46:54Z" level=info msg="Started with sync period every 30 seconds" 
time="2018-07-30T04:47:25Z" level=fatal msg="Get https://<REDCATED>:8200/v1/sys/mounts: x509: certificate signed by unknown authority"
```

**Comment by sunshinekitty** [comment]
You should be able to set the env var VAULT_SKIP_VERIFY=true on the vaultingkube container to skip verifying the self-signed cert.

Otherwise you'll need to install the cert on the container somehow, there isn't a way to do this with the current Dockerfile presently.

**Comment by plombardi89** [comment]
Ah. I ended up creating a new image and putting the certificate in the right place. Thanks!
